mysql:
    driver: com.mysql.jdbc.Driver
    # Change this to your actual database url
    url: jdbc:mysql://localhost/test
    username: user
    password: secure
    
    # Where everything is stored
    table-name: command_whitelister

messages:
    # {0} is replaced by the command name (without the leading slash)
    not-whitelisted: "&cYou do not have permission to execute this command!"
    
